name: Build images
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v5
            - uses: cachix/install-nix-action@v31
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - uses: cachix/cachix-action@v15
              with:
                  name: nvirellia
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            - run: nix build .#packages.aarch64-linux.gaokun
